### ISSUE TITLE
 getSAGGraphs example broken?

### ISSUE THREAD

**Issue by arnima-github** [ices-tools-prod/icesSAG#103]
The help page example for getSAGGraphs looks a bit weird. It boils down to
`plot(getSAGGraphs(8309))`
where only 1 out of 4 plots are produced for this particular cod stock.

The getLandingsGraph help page uses a haddock stock, which happens to work nicely with getSAGGraphs as well,
`plot(getSAGGraphs(8065))`
where all plots are alive and kicking.

So it may be enough to just change the example, but also look into why the current example only produces 1 out of 4 plots.

**Comment by colinpmillar** [comment]
That stock only has one graph:
http://standardgraphs.ices.dk/ViewCharts.aspx?key=8309

So not a bug, but probably better to change the example so as not to confuse.

**Comment by colinpmillar** [comment]
added comment to help file
