### ISSUE TITLE
Ref point BMGT not in graph

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSAG#104]
https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=8553

cant make SSB graph looks like the advice sheet. when setting is add ref point: BMGT graph dissapear. this donot happend with the F graph.

**Comment by martinezinigo** [comment]
i am checking SAG vs Advice and cant solve this case

**Comment by martinezinigo** [comment]
same case as for https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=8879

**Comment by cmspinto** [comment]
Done. 

Check: https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=8879
