### ISSUE TITLE
Show average x/y lines w/ 1,4 doesn't show the "1"

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#105]

**Comment by slarge** [comment]
https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=8973

**Comment by cmspinto** [comment]
the solution is that every year draws a line 0.4 years befors and ends 0.4 years after.

                                seriesXAverageOfPoints.Points.AddXY(listPoints[x - 1].year - 0.4, average_X);
                                seriesXAverageOfPoints.Points.AddXY(listPoints[x - 1].year + 0.4, average_X);


https://standardgraphs.ices.dk/manage/ChartImg.axd?i=charts_0/chart_0_6.png&g=a0ed260e9cb3417585f72da122a94983

![image](https://user-images.githubusercontent.com/8705477/31501542-d3202f3e-af6a-11e7-99d5-30b4a3978b17.png)


https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=8973
