### ISSUE TITLE
ERROR: "relative" SSB output rounded to integers

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#107]
http://standardgraphs.ices.dk/StandardGraphsWebServices.asmx/getSummaryTable?AssessmentKey=8877

<SummaryTableLine>
<Year>1985</Year>
<recruitment xsi:nil="true"/>
<high_recruitment xsi:nil="true"/>
<low_recruitment xsi:nil="true"/>
<low_SSB>1</low_SSB>
<SSB>2</SSB>
<high_SSB>4</high_SSB>
<catches>6427</catches>
<landings>4499</landings>
<discards xsi:nil="true"/>
<low_F>0.361</low_F>
<F>0.645</F>
<high_F>1.242</high_F>
</SummaryTableLine>

but in the advice sheet (and SAG "View source data") SSB 1985 == 2.44496319282666

We don't need 10 decimal places, but it shouldn't be an integer, either.

**Comment by cmspinto** [comment]
there is a rule to choose the number of decimal places for biomass!
