### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by dwall1** [ices-tools-prod/icesSAG#118]
Hi, 

I'm trying to use the function getListStocks to access the ICES data through R however I'm getting a HTTP error. Any suggestions what might be causing this: 

### getListStocks(2017)
Error in download.file(url, destfile = tmp, quiet = TRUE) : 
  cannot open URL 'https://sg.ices.dk/StandardGraphsWebServices.asmx/getSummaryTable?key=-1'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = TRUE) :
  cannot open URL 'https://sg.ices.dk/StandardGraphsWebServices.asmx/getSummaryTable?key=-1': HTTP status was '500 Internal Server Error'

**Comment by dwall1** [comment]
Thanks Scott. I'm using icesSAG_1.2-0

**Comment by slarge** [comment]
Please try the new version of the package:

`library(devtools);  
install_github("ices-tools-prod/icesSAG");    
getListStocks(2017)`

or

`install.packages("icesSAG");  
getListStocks(2017)`

**Comment by dwall1** [comment]
Thanks, this resolved the issue!
