### ISSUE TITLE
SAG/SID common issues to discuss in joint meeting

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/icesSAG#120]
1. (from @mikeydrew) 
**Extended relationships between stockcode ID's**
At the moment, in SID, we only store relations between new stock codes and the old stock codes that were directly replaced. Should this be further developed to allow advice to maintain this by gui and also add the functionality to add relations between stock codes that merge and split? Would this be useful for SAG or do we already have the mapping there?

**Comment by neil-ices-dk** [comment]
2. (from @Lotte-ices-dk)

•	Links between SAG and SID; can we get ‘one entry’ point for updates?
•	Appointing of project leaders for SAG and SID respectively
•	Expectations in terms of ‘speed’ on resolving issues on the project management boards
•	Interfacing with users

**Comment by neil-ices-dk** [comment]
3. (from @odontaster )

Yes, I saw that. My main concern is probably the lack of full correspondence between SAG and SID, which does not allow to directly link the two databases, right?. As I told you last week, in SAG sometimes the stocks with assessment valid for several years, for instance from 2015 to 2017, appear every year, and they link (in 2015 and 2016 in the example) to the same pdf. Furthermore, 2015 and 2016 can show different standard graphs if there are new catches data, for instance. It could be confusing for the end user, and also this thing does not happen every time.

**Comment by colinpmillar** [comment]
As discussed at the TAF meeting, It would also be good to bring TAF in on this. Two aspects came up:
1. Define clearly where the boundary is between TAF and SAG
2. What issues arise if TAF holds the code and results of requests about stock assessment data held in SAG or SID, that were provided via web services using icesSAG and icesSD.
  I think It would be good to have the code online to show people how it was done, and how to do it themselves, while it also serves as a fixed link and record of the data/results that were provided.  But we may need a health warning to say that the results are not live, and to get the most up to date information from the databases you need to run the code again...

**Comment by Milldaz** [comment]
Other issues to consider:
* #45 ...

**Comment by Milldaz** [comment]
Hi All,

Not sure if this is the appropriate spot for it, but I received an e-mail from Jenni Grossmann, Science and Policy Advisor in ClientEarth’s Fisheries team, based in London. I had a chat with her during the MIACO meeting this year.  It describes some of the functionality that NGO-type users are looking for from our databases. Might be useful to keep some of these ideas in mind when we are working on SAG and SID:
 
_Like many colleagues in other NGOs, I spend a lot of my time analysing the annual fishing quotas (comparing them to the underlying ICES advice), and such a database would be incredibly useful as it would help prevent errors, and save us the time associated with manually entering the advice from the pdf-files from the ICES website into our own spreadsheets. 
 
So, I am emailing you to find out what your timeline is (i.e. when you would expect this to be available) and what sort of elements it would include? More specifically, I was wondering if there are plans or if there is any scope for including the following information in this database:
•	The essentials:
o	The ‘stock-code’ which is currently part of the pdf-link of the advice files (e.g. ple-celt for plaice in VIIf-g, or ple.27.7f-g according to the advice for 2018); this would be very useful for matching stocks to the corresponding TACs automatically, based on the stock- and TAC-codes
o	The official ICES advice on total and wanted catch (as specified in the top section of the advice pdf-files, and in some cases in one of the tables further down in the advice, where a stock is only partially subject to the landing obligation)
o	The basis for the official advice (i.e. MSY approach, precautionary approach, management plan, approach to data-limited stocks)
o	The date when the original advice or any subsequent updates were released
o	The link to the respective pdf where the details of the advice can be found
•	Additional information which would be very useful:
o	The stock category (depending on data- and assessment-quality/type)
o	An indication whether or not MSY- or MSY-proxy-based advice is available
o	Any other catch options (e.g. MSY-based catch options where the official advice is based on a management plan)
o	Updated advice (i.e. a record of both the original advice, and any subsequent updates)
o	Possibly even the TAC-code of the relevant TACs covering the stock in question (where this can be easily matched up)_

I have sent her an initial response and told her that we are working on or have a lot of these things already.

Cheers,
David

**Comment by neil-ices-dk** [comment]
Thanks David, as you say many developments in hand but one thing i would be keen to communicate back is that we are deliberately removing the reliance on the pdf as the 'master source', so that the database information becomes the tool and definitive content for the majority of information. So with that, end users such as Jenni should be mindful to not build too much around the pdf (which i'm sure most of them would welcome anyway).

Neil

And thanks for the reminder to setup this meeting now that we have a full suite of discussion point 👍

**Comment by Milldaz** [comment]
Thanks, Neil.  Jenni will be at ICES on the 1st of November.  I was chatting with Scott and we will likely sit down with her and show her what is available and how it can be accessed etc. and discuss this a bit more.  In the meantime I have passed on your comment about moving away from our reliance on the pdf.

**Comment by Milldaz** [comment]
**Minutes from the meeting held 06 Nov 2017**
Present: Scott, Carlos, Mike, Anna O., Colin, Jette, Lotte, David

**New codes**: No mapping if codes are split or merged for stocks; this can be managed by vocabulary (vocab.ices.dk). 

**Links between SAG and SID**: Overlapping information needs only one point of entry to be facilitated for the users, so all advice (sheet) related information should be entered in SAG as this is the db used in the ADGs; the SID will be updated by the WGs when the stock annexes are updated (in terms of basis of the advice, etc.):
- Advice value and associated time-period for when it is valid, as well as advice sentence
- Currently a number of advice fields stored in SID – need to identify which ones to move over to SAG
- Data category: When changed this will affect the stock status table, etc., so there need to be a link between SID and SAG there. This should be changed in SAG during the ADG – then transferred to SID

**Project leads**: For SID: Mike. For SAG: David/Inigo

**Expectations in terms of speed**: Requests/Issues need to be adhered with an expectation and also (reasonable) specification of urgency. Those tasked with the job can then discuss whether the time line is possible and an agreed deadline should be decided.

**Interface with users**: Most changes to interface preferably done before the onset of the advice season. Manuals need to be available for both Advice staff and the end-users. 
- In beginning of the year, the Advice team will have a department meeting with demo of SAG and SID including a description of the planned project timeline + milestones for each system.

**Interface with TAF**: the graphs should be done in SAG but the input surely can come as an output from TAF (in the right format, even). TAF will hold the quality assurance checks (data from TAF, data from web-services, etc.)

**Comment by neil-ices-dk** [comment]
Thanks David - good summary (and decisions)
