### ISSUE TITLE
Allow two advice in the same  year for one stock.

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#122]
* [x] Show more than one line in the historical plots

* [ ] Allow the download to include more than one advice per year

Test case will be the Pandalus
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9206

**Comment by martinezinigo** [comment]
this need to have a tag at the end of the name like _v2, _v3... or date so that we can id at a glance which of the 2-3 stocks with the same name is the newest.
