### ISSUE TITLE
If a stock changes category over time, from 3 to 1, should the qualitative line be in the stock status table?

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesSAG#128]
This happened in a Nephrops stock, 
was Cat 3 in 2015, and cat 1 in 2016-2017.  So the Stock status table could feasably show the qualitative advice from 2015.  

However, you only get that line in the stock status table *if* the category is 3 or 4 in the current year.

**Comment by Milldaz** [comment]
Our stock status tables (all three years) are filled out based on the latest assessment (e.g. the icon for 2015 does not correspond to the assessment in 2015, but rather to the estimate for 2015 from the 2017 model).

So I think upgrading to Category one means filling out all three years based on the assessment, therefore no qualitative line is needed.

**Comment by colinpmillar** [comment]
FYI @sarahlmillar
