### ISSUE TITLE
Include the field purpose

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#135]
The field purpose needs to be included:

 * [x]  - Main page with the list of the stocks
 * [x]  - Stock details (has one of the headers
 * [x]  - Download of the stocks
 * [ ]  - Download of a single stock
 * [ ]  - View source of the stock
 * [x]  - Web services of SAG
 * [x]  - R package of SAG
 * [x] - Edit settings of a stocks
 * [x] Check that already published stocks are for the purpose of advice
 * [ ] Publish the current benchmarks in the database

**Comment by Milldaz** [comment]
Done
