### ISSUE TITLE
Add advice type values into SAG

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesSAG#139]
For example:
Advised landings, basis, data-category
- [ ]  step 1
- [ ] step 2
- [ ] step 3

Ideally these values should be accessible via the DOI for that assessmentKey

Should SID still store the current/final advice values for a stock?

I think this is a joint issue @mikeydrew

**Comment by Milldaz** [comment]
Need to include the period that the advice is valid for

**Comment by cmspinto** [comment]
@David: Isn't this included in the task for the advice view?

**Comment by Milldaz** [comment]
Yep, will close this and move relevant notes to that issue
