### ISSUE TITLE
Template (Recruitment Units missing tonnes)

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#142]
In the Excel template there is a stock that uses Tonnes and it is not available in the template)

https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=9265

Anchovy (Engraulis encrasicolus) in Subarea 8 (Bay of Biscay)
Species: | Engraulis encrasicolus
Stock code: | ane.27.8
Assessment Year: | 2017
Key: | 9265

**Comment by Milldaz** [comment]
Change made for latest version of template
