### ISSUE TITLE
Script to 'recycle' SAG data

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#148]
If changes need to be made after data was initially uploaded using R, there is no template to adjust to upload corrected data. SO:
Write a script to download all the data to R, where changes can be made, then upload it all back to SAG.
Or print out the tables uploaded so they can be copied and pasted into the template for changes.

**Comment by cmspinto** [comment]
@colinpmillar: Isn't this how Martin is working now?

**Comment by Milldaz** [comment]
I think so. As discussed at our meeting I think this issue has been sorted out.
