### ISSUE TITLE
Move fields from SID to SAG

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#150]
Decisions from meeting on 20 Feb 2018 (Carlos, Colin, Mike, David, Anna).

Fields to move to SAG:  (template to be updated)
- [ ] Advice (including date valid from, and period that the advice is valid for)
- [ ] Advice category (PA, MSY etc.)
- [ ] Advice type (catch, F etc.), Ideally these values should be accessible via the DOI for that assessmentKey.
- [ ] Model info (type and name - add 'SCA' and 'Custom')
- [ ] Stock category
	- have vocab in SID, but need in RECO (but need definitions for each sub-category still)

- [ ] Get definitive list of stock categories
    - reduce the number of sub categories (i.e. only single digits since the sub-points are methods)?

**Comment by cmspinto** [comment]
@Milldaz I think this will be replaced by the task of the advice view!

**Comment by Milldaz** [comment]
This is all for the Advice View.
