### ISSUE TITLE
Rowdy column names

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#16]
I'm getting some odd characters in the column names for getFishStockReferencePoints()

`colnames(getFishStockReferencePoints(7607))`
 

> [1] "key"                 "FishStockName"       "AssessmentYear"      "FLim /"              "Fpa /"               "Bpa /"              
>  [7] "Blim /"              "FMSY /"              "MSYBtrigger /"       "Fmanagement /"       "Bmanagement /"       "RecruitmentAge /"   
> [13] "RecruitmentLength /"

Seems like "  /" is being caught in the XML parsing somehow.

**Comment by colinpmillar** [comment]
fixed in development branch
