### ISSUE TITLE
stock code missing

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#164]
Hi, her.27.3031 code is missing form the drop down menu in the excel template. I have exported it as xml and edited the name of the stock manually (changed form her.27.30 to her.27.3031). It uploads the data and I can get the graphs. BUT THE STOCK DOES NOT SHOW UP IN THE LIST OF STOCKS WITH SAGs (I mean the list viewed here below) so I cant select it to make changes etc.
![capture](https://user-images.githubusercontent.com/33519586/39469115-3df81f48-4d26-11e8-9b52-fd1afb9c476c.PNG)

**Comment by Milldaz** [comment]
'Purpose' had not be assigned for the stock.

This has been changed to 'Advice' and now the stock shows up
