### ISSUE TITLE
Assessment Key

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/icesSAG#17]
1) Change the Key on web services to assessmentKey
2) Change the Key on the URL string to assessmentKey
3) Change the label on the stock assessment page to Assessment Key
4) Change all services to refer to AssessmentKey and not Key
5) Add link on assessment page to StockKey (from vocab.ices.dk)

http://standardgraphs.ices.dk/ViewCharts.aspx?key=8114

For reference:
Link to CodeType:
http://vocab.ices.dk/?ref=357
Link to Code:
http://vocab.ices.dk/?codeID=136481

**Comment by colinpmillar** [comment]
on the R side for icesSAG we will

1. update webservice calling functions
2. change R function definition: https://github.com/ices-tools-prod/icesSAG/blob/master/R/getSAGGraphs.R#L26
3. Update documentation: https://github.com/ices-tools-prod/icesSAG/blob/master/R/getSAGGraphs.R#L6
4. Temporarily accept `key` as an argument but warn that it is being depreciated, and to use `AssessmentKey` in the future.

**Comment by cmspinto** [comment]
I think this can be now closed.

**Comment by sarahlmillar** [comment]
Me too - R stuff tested and released

**Comment by colinpmillar** [comment]
Me too - R stuff tested and released

**Comment by neil-ices-dk** [comment]
thanks all, just need to explain all this to the outside world now!
