### ISSUE TITLE
picky WG-plot colors

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#173]
Hello, WGCSE are picky but they have a point. In this plot below for the stock sol.27.7h-k (key=9923) they show relative biomass reference points and also the 2 over 3 year average lines used to apply the category 3 rule. Since the average lines overlap with MSYBtrigger you cant really see much since all is orange...
Is it possible to change one of the colors?

![capture wgcse](https://user-images.githubusercontent.com/33519586/40651789-1482f212-6326-11e8-8509-734bac4faacd.PNG)

**Comment by RuthFG** [comment]
Hello, this is still not solved. Is it possible to change colors ?

**Comment by cmspinto** [comment]
Hi Ruth, no it is not possible currently to change the color!
For this to be possible the decision has to be taken within the group. Technically it is possible but the question is, would the graphs still be standard?
