### ISSUE TITLE
Summary table headings not syncing with data

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#175]
When you add custom series to the **Summary table**, the order matters.

e.g. if I '**Add series to the chart**' as (1,2,3) or (1,3,2), the data will be displayed in different columns added on to the right of the existing columns.

However, in both cases the headers of the summary table will remain the same (i.e. in the same order as they were uploaded).

The headers should always match the data.

This is a good example stock, because the custom series have years in the names:
https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=9930

**Comment by cmspinto** [comment]
Sorry, the stock does not exist anymore!
Can you find it again?

**Comment by Milldaz** [comment]
It is this one now:
https://standardgraphs.ices.dk/manage/editgraphsandtables.aspx?key=9937
