### ISSUE TITLE
Legend getting cropped

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#177]
If too many ref pts and series are used in a plot, the legend gets cropped to the first three then has '...' below. In all cases we need to show all items in the legend (even if this means increasing the y-axis).

e.g. SSB plot in cod.27.5a:
https://standardgraphs.ices.dk/manage/viewgraphsandtables.aspx?key=9659

Generally we need to explore options for automatically placing legends in clear spaces where they fit.

**Comment by cmspinto** [comment]
Solved, it was not taking into account SSB. 
SSB is only added to the legend when a custom series it added. 

![image](https://user-images.githubusercontent.com/8705477/41043396-23b3a1f8-69a4-11e8-91b0-1df612ba4c77.png)
