### ISSUE TITLE
Problems in R historical graph

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#183]
Hello,

I just published the SAG for 4 stocks that went out this Monday.
ane.27.8
cod.27.5b1
had.27.5b
pok.27.5b

There is a problem in all of them with the historical R plot that only shows one line. Could you please have a look? thanks

**Comment by RuthFG** [comment]
it seems solved now, thanks!

**Comment by cmspinto** [comment]
It was a bug in the Recruitment :)
