### ISSUE TITLE
Strange result with Bass

### ISSUE THREAD

**Issue by timearl** [ices-tools-prod/icesSAG#194]
I'm trying to extract the stock assessment for bass, and an empty vector is returned. If I truncate the stock id, it can be found. Minimal example below

```
library(icesSAG)
findAssessmentKey("bss.27.4bc7ad–h", published=TRUE)
# integer(0)

findAssessmentKey("bss.27.4bc7ad", published=TRUE)
# [1]  9207  9959 12957

> findAssessmentKey("bss.27.4bc7ad", published=TRUE, full=TRUE)$StockKeyLabel
# [1] "bss.27.4bc7ad-h" "bss.27.4bc7ad-h" "bss.27.4bc7ad-h"
```

**Comment by colinpmillar** [comment]
thanks Tim - it looks like a bug in the search we are doing in the package

**Comment by colinpmillar** [comment]
So it was an issue with long dash: `–` verses short dash `-`

```r
> "bss.27.4bc7ad–h" == "bss.27.4bc7ad-h"
[1] FALSE
> 
```

The quick fix is to change the stock name in your code to the correct name (i.e. not use the long dash).

But we will also put in a catch in the `findAssessmentKey` to fix this as it could well be a common issue.

THanks,
Colin

**Comment by colinpmillar** [comment]
check and fix implemented here:
https://github.com/ices-tools-prod/icesSAG/commit/f8ef7044dec63061ed2d97f11b22b0b5dc66d244

thanks for letting us know,
Colin

**Comment by timearl** [comment]
Thanks Colin for looking into this and fixing it, it’s much appreciated.

Tim
