### ISSUE TITLE
findAssessmentKey - error

### ISSUE THREAD

**Issue by stjanifani** [ices-tools-prod/icesSAG#204]
When running findAssessmentKey() is called it gives the following error: 

icesSAG::findAssessmentKey(2019)
Error in grepl(EmDash, stock) : 
  regular expression is invalid in this locale

The error is due to: EmDash <- rawToChar(as.raw(150))
rawToChar(as.raw(150)) needs to be replaced with "\u2013".

So it will be:
EmDash <- "\u2013"

**Comment by colinpmillar** [comment]
thanks! we had quite a bit of trouble with this one, can you try running:
```r
  stock <- "whi\x96there"
  if (any(grepl("\\x96", stock))) {
    warning("Please check stock names for 'long dash' ", "\x96", " and replace with -")
    stock <- gsub("\\x96", "-", stock)
  }
```

and see if it runs ok?
Thanks

**Comment by stjanifani** [comment]
Hi Colin,

No, this does not work

I got this script running by doing this and delete the old EmDash line for:

EmDash <- "\u2013"

Kristján



Kristján Kristinsson, fiskifræðingur / Fisheries Scientist
Botnsjávarsvið / Demersal Division
Hafrannsóknastofnun, rannsókna- og ráðgjafastofnun hafs og vatna /
Marine and Freshwater Research Institute,
Skulagata 4, P.Box 1390, 121 Reykjavik, Iceland
Tel.: +354 575 2091
kristjan.kristinsson@hafogvatn.is

________________________________
Frá: Colin Millar <notifications@github.com>
Sent: fimmtudagur, 3. september 2020 10:38
Til: ices-tools-prod/icesSAG <icesSAG@noreply.github.com>
Afrit: Kristján Kristinsson <kristjan.kristinsson@hafogvatn.is>; Author <author@noreply.github.com>
Efni: Re: [ices-tools-prod/icesSAG] findAssessmentKey - error (#204)


thanks! we had quite a bit of trouble with this one, can you try running:

  stock <- "whi\x96there"
  if (any(grepl("\\x96", stock))) {
    warning("Please check stock names for 'long dash' ", "\x96", " and replace with -")
    stock <- gsub("\\x96", "-", stock)
  }

and see if it runs ok?
Thanks

**Comment by colinpmillar** [comment]
Okay doke - I have made a fix and will pull into the master shortly,
Thanks!

**Comment by colinpmillar** [comment]
should be fixed now - let me know if it works ok for you - we will update the CRAN version next week,
thanks for posting the issue!
Colin
