### ISSUE TITLE
historical SAG gone for one stock

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#219]
Hello, last week there was a release of updated advice for the stock (her.27.3031). Therefore I uploaded new SAG graphs for 2020 (https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=14586) that I labelled "advice" and i juts published them. I labelled the previous SAG for this stock in 2020 "advice ( historical)". But now I can only see the updated new SAG in the database and not the previous one (historical). Is that OK?

**Comment by Milldaz** [comment]
Hi Ruth,

"advice (historical)" is just for old assessments from the 90s and 80s that we have been uploading. For re-issued advice you should change the previous SAG to "Replaced". There is also an option to change the initial advice to "Initial advice" - this is done for the summer re-opening etc. But if the reason for the new release was to completely replace the previous advice, then "Replaced" is best.

Either way, the old assessment will not show up anymore in historic plots. If it was a full replacement, we don't need to show the old assessment.

Cheers,
David
