### ISSUE TITLE
getListStocks do not work

### ISSUE THREAD

**Issue by nikosmatsa** [ices-tools-prod/icesSAG#222]
When i am trying to load the 2015 for example data i get 
`
meta <- getListStocks(2015)
GETing ... http://sg.ices.dk/StandardGraphsWebServices.asmx/getListStocks?year=2015
Warning messages:
1: http status message: Server error: (500) Internal Server Error 
2: in SAG API - Missing parameter: token.
 
meta
NULL
`

why? how can i fix it?

**Comment by cmspinto** [comment]
Working now but there is a new API for SAG that should be used
