### ISSUE TITLE
error; DATSU has stopped checking data

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSAG#224]
Hello,

<img width="940" alt="redfish DATSU has stopped chekcing data" src="https://user-images.githubusercontent.com/33519586/134866378-42fab19d-4da0-486a-8967-fb9d5d760cf1.PNG">

I have problems uploading the attached xml file. I downloaded an xml from SAG (https://standardgraphs.ices.dk/manage/viewgraphsandtables.aspx?key=16812), modified the content of custom column 1 based on a request from ACOM and tried to upload again. I get an error. 

The xml I tried to upload is in here: 

[reb.2127.sp-2021-220.zip](https://github.com/ices-tools-prod/icesSAG/files/7234366/reb.2127.sp-2021-220.zip)

Can you help?

**Comment by cmspinto** [comment]
This was solved
