### ISSUE TITLE
Cannot download summary of initial advice

### ISSUE THREAD

**Issue by hgerritsen** [ices-tools-prod/icesSAG#225]
It doesnt seem to be possible to download initial advice, I can only get published advice, even when i used the same token that i used to upload the data
```
options(icesSAG.use_token = TRUE)
getSAG('ank.27.78abd',2022,data='summary',purpose='InitAdvice')
```

**Comment by Milldaz** [comment]
Hi Hans, I have checked and there is no filter excluding non-Advice assessments from the download. In 2022 there are only two assessments for ank.27.78abd - 'Bench' and 'Advice'.

**Comment by hgerritsen** [comment]
Hi David
Then how do I get the 2022 summary table? None of these work:

library(icesSAG)

# this works
getSAG('ank.27.78abd',2021,data='summary',purpose='Advice')

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='Advice')

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='InitAdvice')

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='Bench')

# try again with token
cat("# Standard Graphs personal access token",
    "SG_PAT=d0316196-6c9b-4f00-b3a2-ec1c0ec1be19",
    sep = "\n",
    file = "~/.Renviron_SG")
options(icesSAG.use_token = TRUE)

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='Advice')

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='InitAdvice')

# returns empty list
getSAG('ank.27.78abd',2022,data='summary',purpose='Bench')

Thanks,
Hans

**Comment by Milldaz** [comment]
For me at least, this line gets both 2022 assessments:
getSAG('ank.27.78abd',2022,data='summary') 

It seems that the purpose parameter doesn't do anything actually, since I also get both assessments with either of these:
getSAG('ank.27.78abd',2022,data='summary',purpose='Bench') 
getSAG('ank.27.78abd',2022,data='summary',purpose='Advice') 
getSAG('ank.27.78abd',2022,data='summary',purpose='InitAdvice')

**Comment by colinpmillar** [comment]
Hi all,
Yes the purpose parameter (which should filter on purpose) seems not to have been implemented! So I will get onto that.

However, I also get a dataframe with Bench and Advice versions of the summary table for the 2022.

Maybe it is a package version issue?

Do you get anything when you look at the http pages from your browser?

https://sg.ices.dk/Manage/StockAssessmentGraphsWithToken.asmx/getSummaryTable?assessmentKey=17280&token=<paste<https://sg.ices.dk/Manage/StockAssessmentGraphsWithToken.asmx/getSummaryTable?assessmentKey=17280&token=%3cpaste> your token here>

**Comment by hgerritsen** [comment]
Hi Colin, David

The webservice works for me (with my own token). So the problem seems to be somewhere in the R function.
I installed the lastest version of icesSAG (v 1.4.0) and I still get nothing for 2022 with or without the option icesSAG.use_token. Maybe it fails to identify the correct assessmentKey?

Hans

**Comment by LApetre** [comment]
Hi all,
There was actually an issue with one of the web service methods (stock list method not summary data) that could be related to this. That is fixed now.
Could you give the R method another try Hans and let us know if that helped?
Best,
Laura

**Comment by hgerritsen** [comment]
Yes, it worked!
Thanks all.
Hans
