### ISSUE TITLE
Update the textual and digital citation for SAG stocks

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/icesSAG#23]
suggestion:

[Full Stock title], Assessed in [AssessmentYear], Assessment Key [AssessmentKey]. ICES Stock Assessment Database. ICES, Copenhagen

Sandeel (Ammodytes spp.) in Divisions 4.b and 4.c, Sandeel Area 1r (central and southern North Sea, Dogger Bank), Assessed in 2017, Assessment Key 8229. ICES Stock Assessment Database. ICES, Copenhagen

Furthermore, assign DOI's and include metadata

- [x] generic citation
- [x] DOI for advice sheet
- [ ] DOI for SAG page - moved to #108

**Comment by neil-ices-dk** [comment]
final generic citation:
ICES Stock Assessment Database. Copenhagen, Denmark. ICES. [accessed date]. http://standardgraphs.ices.dk.

Specific citation:
[Full Stock title], Assessed in [AssessmentYear], Assessment Key [AssessmentKey]. ICES Stock Assessment Database. Copenhagen, Denmark. ICES. [accessed date].

**Comment by colinpmillar** [comment]
@cmspinto  I can do this?  It is just a change to the text on the SAG landing page no?

**Comment by colinpmillar** [comment]
Add to species page, below Data Category - 
Citation: ICES Stock Assessment Database. Copenhagen, Denmark. ICES. [accessed date]. 
DOI: for the advice sheet - find out where this is stored

**Comment by neil-ices-dk** [comment]
actually the idea was to associate a DOI to the stock assessment key and to SAG, rather than the advice sheet (assuming you mean the PDF). so it would resolve to this http://standardgraphs.ices.dk/ViewCharts.aspx?key=8435 as a pure digital resource. If we direct people to the PDF then they are at a dead end

**Comment by neil-ices-dk** [comment]
@colinpmillar - Hans manages the database for DOI's

**Comment by neil-ices-dk** [comment]
done on ICES website
