### ISSUE TITLE
Create a new homepage for Advice and Scenarios Database

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#233]
We have now the subdomain asd.ices.dk we also need a homepage for the platform.

It can be similar to SAG.

![image](https://user-images.githubusercontent.com/8705477/220935224-110ab5e1-fe45-4d86-bef3-a7cb6b46f635.png)

View advice and scenarios records: http://asd.ices.dk/AdviceList
Manage Advice and Scenarios Database: http://asd.ices.dk/AdviceList/Manage
 Advice and Scenarios Database API: http://asd.ices.dk/AdviceList/API

**Comment by lucalamoni** [comment]
@cmspinto @colinpmillar and I were wondering if it could be possible to add also the link to the ASD R package (https://ices-tools-prod.r-universe.dev/icesASD)?

**Comment by cmspinto** [comment]
I think @Milldaz David and @neil-ices-dk  are still working on the homepage.

**Comment by neil-ices-dk** [comment]
> I think @Milldaz David and @neil-ices-dk are still working on the homepage.

i am poised and ready when i get some content/links 🙂

**Comment by cmspinto** [comment]
[Advice and Scenarios Database webpage.docx](https://github.com/ices-tools-prod/icesSAG/files/11028945/Advice.and.Scenarios.Database.webpage.docx)

**Comment by neil-ices-dk** [comment]
@Milldaz and @cmspinto there is a small corruption in your Word file, can you take a look please;
I noted David's comment on meta-data, is somebody able to help him with that?
![image](https://user-images.githubusercontent.com/23527005/226651722-aac9da08-41a4-49f6-984f-3f289d832a3e.png)

**Comment by Milldaz** [comment]
ICES provides scientific advice on ecosystem services and effects to governments and international regulatory bodies that manage the North Atlantic Ocean and adjacent seas. The key advice values and catch scenarios from fishing opportunity advice sheets that are published in the [ICES library](https://ices-library.figshare.com/) can be accessed on this page.

No help on the metadata part yet

**Comment by Milldaz** [comment]
![ASD Webpage image](https://user-images.githubusercontent.com/12511566/226858343-f7eb8b44-8136-49dc-890a-5b265a5ba617.JPG)

**Comment by neil-ices-dk** [comment]
@Milldaz just returning to this, are you sure about the URL in the citation?
ICES Advice and Scenarios Database. Copenhagen, Denmark. ICES. [accessed date]. https://asd.ices.dk/AdviceList 

normally this would be the landing page of the system - https://asd.ices.dk

**Comment by neil-ices-dk** [comment]
@cmspinto just doing my edits and noticed in David's Word doc [Advice and Scenarios Database webpage.docx](https://github.com/ices-tools-prod/icesSAG/files/11028945/Advice.and.Scenarios.Database.webpage.docx) there are a number of corrections for you to do on the application pages

**Comment by neil-ices-dk** [comment]
@cmspinto and @Milldaz i think the only thing missing is the meta data link record 
https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx

**Comment by lucalamoni** [comment]
@cmspinto @Milldaz @neil-ices-dk I just noticed that the image on the page https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx still looks a bit blurry. Could we ask Comms to help with this?

**Comment by neil-ices-dk** [comment]
> @cmspinto @Milldaz @neil-ices-dk I just noticed that the image on the page https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx still looks a bit blurry. Could we ask Comms to help with this?

Comms can't help, its SharePoint, I will fix it

**Comment by Milldaz** [comment]
> @Milldaz just returning to this, are you sure about the URL in the citation? ICES Advice and Scenarios Database. Copenhagen, Denmark. ICES. [accessed date]. https://asd.ices.dk/AdviceList
> 
> normally this would be the landing page of the system - https://asd.ices.dk

I'm not sure at all, didn't put that much thought into it. I agree that the landing page of the system is better. Can you change that?

**Comment by Milldaz** [comment]
> @cmspinto just doing my edits and noticed in David's Word doc [Advice and Scenarios Database webpage.docx](https://github.com/ices-tools-prod/icesSAG/files/11028945/Advice.and.Scenarios.Database.webpage.docx) there are a number of corrections for you to do on the application pages

I think a lot (if not all) of these have now been addressed.

**Comment by Milldaz** [comment]
> @cmspinto and @Milldaz i think the only thing missing is the meta data link record https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx

I will leave this in the capable hands of @cmspinto

**Comment by neil-ices-dk** [comment]
> > > @cmspinto @Milldaz @neil-ices-dk I just noticed that the image on the page https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx still looks a bit blurry. Could we ask Comms to help with this?
> > 
> > 
> > Comms can't help, its SharePoint, I will fix it
> 
> The specification for the size of the image is really small (300x370px is tiny). I can save a larger version if those specification are not strict

@Milldaz the critical issue is the ratio between the H/W, if the image is quite tall then it will look funny when rendered. Could you make a version at a higher resolution, but perhaps a bit shorter than it currently is.

**Comment by neil-ices-dk** [comment]
> > @cmspinto just doing my edits and noticed in David's Word doc [Advice and Scenarios Database webpage.docx](https://github.com/ices-tools-prod/icesSAG/files/11028945/Advice.and.Scenarios.Database.webpage.docx) there are a number of corrections for you to do on the application pages
> 
> I think a lot (if not all) of these have now been addressed.

@cmspinto for example:

1.	Replace:
“Here you can find the advice values, and catch options table from ICES fish stock assessments as presented in published advice. You can:”
With:

https://asd.ices.dk/AdviceList 
_Here you can find the advice values and catch scenarios tables from ICES fish stock assessments as presented in the published advice._

I couldn't check the manage page https://asd.ices.dk/AdviceList/Manage as it doesn't load

**Comment by Milldaz** [comment]
> > > > @cmspinto @Milldaz @neil-ices-dk I just noticed that the image on the page https://www.ices.dk/data/assessment-tools/Pages/advice-scenarios-database.aspx still looks a bit blurry. Could we ask Comms to help with this?
> > > 
> > > 
> > > Comms can't help, its SharePoint, I will fix it
> > 
> > 
> > The specification for the size of the image is really small (300x370px is tiny). I can save a larger version if those specification are not strict
> 
> @Milldaz the critical issue is the ratio between the H/W, if the image is quite tall then it will look funny when rendered. Could you make a version at a higher resolution, but perhaps a bit shorter than it currently is.

Larger files, one shorter:
![ASD Webpage image LRG](https://user-images.githubusercontent.com/12511566/236201499-025b35ad-acd2-4698-b918-773f0dc8c81e.png)
![ASD Webpage image LRG_shorter](https://user-images.githubusercontent.com/12511566/236201506-ca7826f2-8d94-4ec1-a598-867db472cf14.png)

**Comment by neil-ices-dk** [comment]
@lucalamoni the reason i emailed about online advice is that we were told it was still in development and not to be anchored - so can we keep the link in the right hand panel to the online advice?

the page is ready, just need the link to the meta data

**Comment by lucalamoni** [comment]
@neil-ices-dk an expert in a meeting this morning was not able to access ASD/manage section from here:
![Screenshot 2023-05-10 103624](https://github.com/ices-tools-prod/icesSAG/assets/32708094/26c93694-6f69-4347-99bd-3e51b8729626)
It seems to work for me now but I thought it was useful to report it.

**Comment by neil-ices-dk** [comment]
@lucalamoni i updated the link this morning (from Carlos's post above) at about 10:15, so if the user tried before that he would have indeed had a dead link ⚰

**Comment by neil-ices-dk** [comment]
btw - was wondering if this one should be renamed to "View and **Download** Records" to make it clear 
![image](https://github.com/ices-tools-prod/icesSAG/assets/23527005/22647bc8-380a-437c-af09-99b2b9ad844e)

**Comment by LApetre** [comment]
The metadata link is:
http://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/710f7368-7f51-43dc-b0ac-8cc1788eb23b

**Comment by neil-ices-dk** [comment]
thanks @LApetre i have added that and consider this complete, so will now link off from the https://www.ices.dk/data/assessment-tools/Pages/default.aspx menu
