### ISSUE TITLE
token file ~/.Renviron_SG altered by calls to icesSAG functions

### ISSUE THREAD

**Issue by iagomosqueira** [ices-tools-prod/icesSAG#239]
I have setup the .Renviron_SG file with a new token and issued

```
options(icesSAG.use_token = TRUE)
```

after I call `findAssessmentKey('sol.27.4', year=ay, published = FALSE)`, the file is modified and is no longer valid. 

Same happens with `icesSAG::uploadStock(info, fishdata)`

The `SG_PAT=` text disappears and the token is changed to a different one.

What could be causing this?

**Comment by colinpmillar** [comment]
I have no idea! thanks I will look into it asap

**Comment by colinpmillar** [comment]
@iagomosquiera  , can you try running:

```r
readRenviron(.sg_renviron)
```

and seeing if that changes the file?  I am a bit at a loss no this one, maybe we need to have a quick teams chat to investigate.

**Comment by iagomosqueira** [comment]
Yes, it does change it. If I set the example token in the README, I get

`b240a403-312b-4d46-810d-d90506ec7b95`

after running `readEnviron` , but only the first time it is run in a session.  So if I rewrite it back, it is not changed when `readEnviron` is called again in the same session.

**Comment by colinpmillar** [comment]
OK - well thats something... readEnviron is a base R function, so maybe there is a linux permissions issue going on?  I would need to investigate on a linux machine or i'll catch you for a video chat at some point. A Curious one!

**Comment by colinpmillar** [comment]
Hi!
We no longer use this method to pass tokens, so I am closing this (it will remain a curiousity!)
