### ISSUE TITLE
In the ASD web service commas "," seem to be substituted with ";" in the advice sentences.

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-prod/icesSAG#246]
See examples here:
https://asd.ices.dk/api/getAdviceViewRecord?Year=2022

**Comment by lucalamoni** [comment]
<img width="557" alt="image" src="https://github.com/ices-tools-prod/icesSAG/assets/32708094/08f0fc68-5664-41b0-8ea1-0c0c2898846b">
Hi @LApetre , any update on this issue? Thank you!

**Comment by LApetre** [comment]
Hi Luca.

This was happening because having "," in the advice sentence interferes with the CSV format download. 

I now modified this specific API method to get the initial sentence instead, so you shouldn't have this problem anymore.

**Comment by lucalamoni** [comment]
Great!! Thank you so much @LApetre !!
