### ISSUE TITLE
Not able to access stock assessment data

### ISSUE THREAD

**Issue by franemadiraca** [ices-tools-prod/icesSAG#254]
Hello,

I have been using the icesSAG::getSAG function for a long time now without any issues. However, today all I get is an error message. Here is my code:

icesSAG::getSAG(stock = "fle.27.2223", year = 2022)

And here is the error message:

GETing ... http://sg.ices.dk/StandardGraphsWebServices.asmx/getListStocks?year=2022
Error in curl::curl_fetch_memory(url, handle = handle) : 
Timeout was reached: [sg.ices.dk] Connection timeout after 10003 ms
list()
Warnmeldung:
In sag_get(uri) : Attempt to access webservice failed:
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [sg.ices.dk] Connection timeout after 10003 ms

Can you please assist with this issue?

Kind regards

**Comment by colinpmillar** [comment]
hi!

If you install from github or from r-universe most things should work as they should... 

install.packages("icesSAG", repos = c("https://ices-tools-prod.r-universe.dev", "https://cloud.r-project.org"))

For example:

library(icesSAG)
library(dplyr)
options(icesSAG.use_token = FALSE)
getListStocks(2024) |> filter(Status != "Published")

options(icesSAG.use_token = TRUE)
getListStocks(2024) |> filter(Status != "Published")


The only thing missing is the upload capability...
I will be pushing to CRAN soon.

Cheers,
Colin

**Comment by colinpmillar** [comment]
@franemadiraca can you update your version of icesSAG and let me know if you are able to download the stocks you are interested in?

Then I will close the issue - thanks!

**Comment by franemadiraca** [comment]
Hello!

I have just tested it again a few days ago without reinstalling both in R
on my laptop and in the R Server that I am using and it's working fine.
Thank you for responding!

Cheers,
Frane
