### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#257]

**Comment by Milldaz** [comment]
- [ ] Make recruitment units compulsory if there are values entered for recruitment
- [ ] Check that axis titles are changed if units are changed in SAG after upload

**Comment by lucalamoni** [comment]
@LApetre if you need an example to check the mismatch between the axis label (billions) and actual values (millions) we found this in https://standardgraphs.ices.dk/ViewCharts.aspx?key=18515, I'm not sure if it is something present in other stocks as well.
![Image](https://github.com/user-attachments/assets/6c6184f5-854f-472a-8956-3ebb8aad9c27)
![Image](https://github.com/user-attachments/assets/70114d7c-db2a-4ff1-8b4b-4854f62ce8d2)

**Comment by LApetre** [comment]
@lucalamoni 
In this case, the values are in millions and the unit is thousands, so the axis label billions looks correct from my perspective. 
Thanks for keeping an eye out though.

**Comment by lucalamoni** [comment]
@LApetre my bad, I misunderstood the values. Makes sense now that you clarified it :)
Thank you!
