### ISSUE TITLE
"missing columns"?

### ISSUE THREAD

**Issue by einarhjorleifsson** [ices-tools-prod/icesSAG#3]
doing:

```
library(icesSAG)
str(getSummaryTable(2016, "cod-iceg"))
```

does not return columns for "HR" (harvest rate) nor "Biomass Age 4+" (reference biomass) values (as appears in the summary table)

mind you, one also gets the same lack of columns via e.g.:
http://standardgraphs.ices.dk/StandardGraphsWebServices.asmx/getSummaryTable?key=7856

but if one goes:
http://standardgraphs.ices.dk/ViewCharts.aspx?key=7856
one gets the whole truth (and nothing but the truth :-). so the data must be within the system somewhere. but somewhere along the path the pipe seems to be broken. the alternative is of course that i got things confused.

regards,
einar

**Comment by colinpmillar** [comment]
Hi Einar we are working to get raw data available via webservices

**Comment by slarge** [comment]
Hi Einar,
 Raw data is indeed provided via webservices. Stock Assessment Graph outputs have a few columns (e.g., "stockSizeDescription" and "fishingPressureDescription") that are used to modify the "standard" columns like SSB and F. The "description" columns allow each stock to be a tad different, while still maintaining consistency.
