### ISSUE TITLE
Implement rounding rules

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSAG#43]
follow ACOM document

**Comment by colinpmillar** [comment]
From Ruth:
Hi, it seems that the rounding is not applied to the custom columns. See here cod.27.22-24 stock

![capture](https://user-images.githubusercontent.com/33519586/38567908-d5992474-3cd6-11e8-8eee-e7d737470dfb.PNG)

**Comment by colinpmillar** [comment]
from @RuthFG
Hello,

For these 2 stocks, when we download the data as a .doc document we don’t get the right numbers . Can you check?

https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9428
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=9415

See attachment
SAG rounding issue.docx

Ruth

**Comment by colinpmillar** [comment]
This has been fixed now - small issue remain with the customs colums, but in general this is complete
