### ISSUE TITLE
Final advice tonnage, Advice sentence and Basis for the advice

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSAG#45]
We need to archive the final advice tonnage (and possibly text) and include it on the download and tables.
Will need to be updated at the end of the year (?) discuss with LW, DM and CP. Do SLD archive the advice text already?

**Comment by martinezinigo** [comment]
discuss with Scott and Lotte, MIke, etc
SAG will take form SD the number of years for which the advice is valid for. 
SD will archive this information. The value need to be in tonnes with NO TEXT. There may need a box to archive the advice sentence. Dealing with ranges need consideration and Landing obligation.

**Comment by slarge** [comment]
It is indeed in SD - I guess we need to decide where it makes most sense to live.

**Comment by colinpmillar** [comment]
@Milldaz will we raise this again?  Or have we dealt with it?
