### ISSUE TITLE
Reopening of advice: how to approach/archive?

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSAG#47]

**Comment by martinezinigo** [comment]
inform Lotte:
new advice means new data and graphs and only the newest  entry of a stock in SAG per year.

**Comment by Milldaz** [comment]
We will create a new field called reason. 
In this new field called reason the possible options are "benchmark", "advice", "initial advice"

Add to front page with filter.
This should also be replicated in the webservices output.

**Comment by colinpmillar** [comment]
All done now I think!
