### ISSUE TITLE
findAssessmentKey(stock = NULL) length = 0?!

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#59]
It should return all stock keys published in 2016... what's going on?
```
icesSAG::findAssessmentKey(stock = NULL,
                   year = 2016,
                   full = TRUE)
```

> GETing ... http://sg.ices.dk/StandardGraphsWebServices.asmx/getListStocks?year=2016
> [1] AssessmentKey    StockKeyLabel    StockDatabaseID  StockKey         StockDescription
> [6] Status           AssessmentYear   SpeciesName     
> <0 rows> (or 0-length row.names)

**Comment by colinpmillar** [comment]
Probably a bug that crept in –

Will add this case to the tests and update on Master for now
