### ISSUE TITLE
cod.27.47d20 not in template

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#63]
cod.27.47d20 was listed as cod.27.3a47d in the .xlsx template and silently failed to upload to SAG. 1) Better error handling on xml upload (e.g., "Stock not recognized", etc). 2) Make sure the link between the old stock code for cod-347d and cod.27.47d20 is maintained - right now historical assessments are not showing up on the 5 year plots.

**Comment by colinpmillar** [comment]
This issue has been split into two separate more general issues
