### ISSUE TITLE
Adding extra columns to the catches

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#68]

**Comment by cmspinto** [comment]
Thanks – is it also possible to have a BMS column in the table output.

SL

From: Carlos Pinto 
Sent: 04 May 2017 10:41
To: Scott Large <scott.large@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: RE: Adding extra columns to the catches

This is what I changed it for:

 

My guess is that is used the cached image. 

Best, 

Carlos

From: Scott Large 
Sent: quinta-feira, 4 de maio de 2017 10:37
To: Carlos Pinto <carlos@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: RE: Adding extra columns to the catches

It looks like you changed the color – to another color that is already in use 
LandingsBMS should be BMS landings

 

From: Carlos Pinto 
Sent: 04 May 2017 08:51
To: Scott Large <scott.large@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: RE: Adding extra columns to the catches

Done both .

The color was already changed, I just hadn’t published. 

Best, 

Carlos

From: Scott Large 
Sent: quinta-feira, 4 de maio de 2017 08:16
To: Carlos Pinto <carlos@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: RE: Adding extra columns to the catches

Hi Carlos,
Thank you for your quick work. 2 things: 1) Could we change LandingsBMS to BMS landings? 2) I think for this year it doesn’t matter because BMS are minimal, but in the future we should probably add another color so we don’t have 2 bars plotting the same color.

Thanks again,

SL

From: Carlos Pinto 
Sent: 03 May 2017 14:51
To: Scott Large <scott.large@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: RE: Adding extra columns to the catches

Forgot to had the image, 

Should look like this:

 

From: Carlos Pinto 
Sent: quarta-feira, 3 de maio de 2017 14:51
To: Scott Large <scott.large@ices.dk>
Cc: David Miller <david.miller@ices.dk>; Inigo Martinez <inigo@ices.dk>; Colin Millar <colin.millar@ices.dk>
Subject: Adding extra columns to the catches

Hi Scott, 

Just updated SAG and now the Catches graph has tow changes:

a)	Accepts more than one extra column

b)	It accepts any column in the extra columns (before it had to be a custom column)!


Best, 

Carlos


Carlos Pinto
Data Systems Analyst
International Council for the Exploration of the Sea 
Email: carlos@ices.dk
Web: www.ices.dk

Tel: +45 3338 6713 	Fax: +45 3393 4215
H.C. Andersens Boulevard 44-46
1553 Copenhagen V. Denmark
 SAVE PAPER - Please do not print this e-mail unless absolutely necessary

**Comment by colinpmillar** [comment]
Testing!

**Comment by Milldaz** [comment]
BMS done.
