### ISSUE TITLE
Find nicer 4th colour ;)

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesSAG#69]
![image](https://cloud.githubusercontent.com/assets/1502848/25713220/4509b354-30f4-11e7-9b69-812a2158c4df.png)

hey @cmspinto  Can we set colour using RGB? (this plot is from https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=8429)

**Comment by colinpmillar** [comment]
Also, this is has changed the colour for stock already through review... might be best to set it to something only slightly different to the previous orange....  Or set the colour only in the case of BMS landings?

**Comment by cmspinto** [comment]
It is not only about the 4th color.
Users can put a maximum of 20 series in a chart. 
I think we need to find at least 3 other nice colors 

Carlos

**Comment by colinpmillar** [comment]
I think Carlos fixed this

**Comment by Milldaz** [comment]
Talk with our new house designer to find a new color scheme.

**Comment by colinpmillar** [comment]
Have emailed Ole and he is going to come up with a set of colours for now, but will look to developing an ICES palette for the future

**Comment by Milldaz** [comment]
This will be done when setting up the new graphics
