### ISSUE TITLE
Stock Status table squished on .doc download

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSAG#73]
The margins on the .doc file generated from SAG  (2.54cm all around) differs from ICES advice standard margins (top - 2.75cm, bottom - 3cm, right - 1.59, left - 2cm). The .png file generated by SAG is likely an appropriate size, but it is probably being rescaled by word. When people are copying and pasting from the .doc output, the scaling is preserved and the table looks rowdy in the new advice. 

![image](https://cloud.githubusercontent.com/assets/5000131/25742660/bebb1764-3190-11e7-9013-560fb11b20e2.png)

**Comment by slarge** [comment]
Hold on - the stock status table now is miniature! 



[8949_ple.27.7d_2017_8949_201788141301.docx](https://github.com/ices-tools-prod/icesSAG/files/1208143/8949_ple.27.7d_2017_8949_201788141301.docx)

**Comment by Milldaz** [comment]
Make standard width of 17.5 cm (so it can be copied and pasted directly into the advice sheets
