### ISSUE TITLE
In the view source add the custom columns (all that have been uploaded)

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#82]
two things to do:
- [x] add custom data
- [x] add custom ref points?

**Comment by cmspinto** [comment]
An example of this would be:
https://standardgraphs.ices.dk/manage/ViewSourceDataRestrictedUser.aspx?key=8518

**Comment by colinpmillar** [comment]
annother example:
https://standardgraphs.ices.dk/ViewCharts.aspx?key=8036

**Comment by martinezinigo** [comment]
this  is a long term development. Colin to create a label

**Comment by colinpmillar** [comment]
Began this here:
http://tfs2017:8080/tfs/Source/Fisheries/_versionControl/changeset/4634

**Comment by colinpmillar** [comment]
Here is a good one for custom ref points:
http://standardgraphs.ices.dk/ViewCharts.aspx?key=8296

**Comment by colinpmillar** [comment]
Reference points added here:
http://tfs2017:8080/tfs/Source/Fisheries/_versionControl/changeset/4637
