### ISSUE TITLE
Customize the title of the historical plots (individualy)

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-prod/icesSAG#88]
In some cases the title of the historical plot might be different of the "mother" plot.
Example is the stock: 
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=8845
where the mother stock is F and HR but the historical is only F

**Comment by Milldaz** [comment]
Problem solved: added a setting to choose whether or not a different title was needed for the historical plots
