### ISSUE TITLE
Make average lines (2:3 rule for Cat 3) lighter colour

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/icesSAG#90]
So they show up when plotted directly over the main survey line

**Comment by cmspinto** [comment]
This is now on test. The changes have been implemented

**Comment by cmspinto** [comment]
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=8964

**Comment by Milldaz** [comment]
Orange used now.
